spring:
  application:
    name: firstproject
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webdb
    username: dbuser
    password: 12345
  jpa:
    properties :
      hibernate:
        format_sql : true
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8094

logging:
  level:
    org:
      thymeleaf: INFO
      hibernate: TRACE
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
